## ML Zoomcamp 2023 - Homework #1

In [25]:
# Import libraries
import pandas as pd
import wget
import numpy as np


In [2]:
# Load Data
url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv'
filename = wget.download(url)

### Question 1

In [3]:
pd.__version__

'1.5.3'

In [4]:
wget.__version__

'3.2'

### Question 2

In [5]:
data = pd.read_csv("housing.csv")
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [6]:
len(data.columns)

10

### Question 3

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [18]:
data.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [16]:
# Check missing values
data.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

### Question 4

In [9]:
data.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [10]:
len(data.ocean_proximity.unique())

5

### Question 5

In [11]:
data.query('ocean_proximity == "NEAR BAY"')['median_house_value'].mean()

259212.31179039303

In [12]:
data.query('ocean_proximity == "NEAR BAY"').describe()

longitude     latitude  housing_median_age   total_rooms  \
count  2290.000000  2290.000000         2290.000000   2290.000000   
mean   -122.260694    37.801057           37.730131   2493.589520   
std       0.147004     0.185434           13.070385   1830.817022   
min    -122.590000    37.350000            2.000000      8.000000   
25%    -122.410000    37.730000           29.000000   1431.250000   
50%    -122.250000    37.790000           39.000000   2083.000000   
75%    -122.140000    37.907500           52.000000   3029.750000   
max    -122.010000    38.340000           52.000000  18634.000000   

       total_bedrooms   population   households  median_income  \
count     2270.000000  2290.000000  2290.000000    2290.000000   
mean       514.182819  1230.317467   488.616157       4.172885   
std        367.887605   885.899035   350.598369       2.017427   
min          1.000000     8.000000     1.000000       0.499900   
25%        289.000000   718.250000   275.000000       2.834750   
50%        423.000000  1033.500000   406.000000       3.818650   
75%        628.750000  1495.000000   599.250000       5.054425   
max       3226.000000  8276.000000  3589.000000      15.000100   

       median_house_value  
count         2290.000000  
mean        259212.311790  
std         122818.537064  
min          22500.000000  
25%         162500.000000  
50%         233800.000000  
75%         345700.000000  
max         500001.000000

### Question 6

In [13]:
mean_bedrooms = data['total_bedrooms'].mean()
print(f"Initial average of total_bedrooms: {mean_bedrooms}")

Initial average of total_bedrooms: 537.8705525375618


In [14]:
data['total_bedrooms'].fillna(mean_bedrooms, inplace=True)

In [15]:
updated_mean_bedrooms = data['total_bedrooms'].mean()
print(f"Average of total_bedrooms after filling NaN values: {updated_mean_bedrooms}")


Average of total_bedrooms after filling NaN values: 537.8705525375617


### Question 7

In [22]:
selected_data = data[data['ocean_proximity'] == "ISLAND"][['housing_median_age', 'total_rooms', 'total_bedrooms']]
selected_data

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [23]:
# Get the underlying NumPy array:
X = selected_data.values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [24]:
# Compute the matrix-matrix multiplication between the transpose of X and X:
XTX = X.T.dot(X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [26]:
# Compute the inverse of XTX:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [27]:
# Create an array y: 
Y = np.array([950, 1300, 800, 1000, 1300])

In [28]:
# Multiply the inverse of XTX with the transpose of X, and then the result by y:
w = XTX_inv.dot(X.T).dot(Y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [29]:
# Get the value of the last element of w:
last_element = w[-1]
print(last_element)

5.699229455065565
